"""initial schema

Revision ID: 9fcfb64b68e2
Revises:
Create Date: 2026-09-14 16:15:19.364144
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "9fcfb64b68e2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column(
            "criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("coin_reward", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column("secret", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
    )
    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_achievements_slug"), ["slug"], unique=True)

    op.create_table(
        "badges",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.Column(
            "criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("secret", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_badges")),
    )
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_badges_slug"), ["slug"], unique=True)

    op.create_table(
        "challenges",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("skill_slug", sa.String(length=40), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column(
            "concept_slugs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("starter_code", sa.Text(), nullable=False),
        sa.Column("broken_code", sa.Text(), nullable=True),
        sa.Column("reference_solution", sa.Text(), nullable=False),
        sa.Column("solution_explanation", sa.Text(), nullable=False),
        sa.Column(
            "tests",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "requires_packages",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("setup_code", sa.Text(), nullable=False),
        sa.Column(
            "hints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "explanation_prompts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expected_complexity", sa.String(length=40), nullable=True),
        sa.Column("baseline_code", sa.Text(), nullable=True),
        sa.Column("target_speedup", sa.Float(), nullable=True),
        sa.Column("par_seconds", sa.Integer(), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=False),
        sa.Column("memory_limit_mb", sa.Integer(), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenges")),
    )
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_challenges_category"), ["category"], unique=False)
        batch_op.create_index("ix_challenges_category_tier", ["category", "tier"], unique=False)
        batch_op.create_index(batch_op.f("ix_challenges_skill_slug"), ["skill_slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_challenges_slug"), ["slug"], unique=True)

    op.create_table(
        "concepts",
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("skill_slug", sa.String(length=40), nullable=False),
        sa.Column("skill_node_slug", sa.String(length=80), nullable=True),
        sa.Column("base_difficulty", sa.Integer(), nullable=False),
        sa.Column("max_tier", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "examples",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "common_mistakes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "real_world_usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "visualization",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_difficulty BETWEEN 1 AND 10", name=op.f("ck_concepts_base_difficulty_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concepts")),
    )
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_concepts_category"), ["category"], unique=False)
        batch_op.create_index(
            "ix_concepts_category_difficulty", ["category", "base_difficulty"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_concepts_skill_node_slug"), ["skill_node_slug"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_concepts_skill_slug"), ["skill_slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_concepts_slug"), ["slug"], unique=True)

    op.create_table(
        "knowledge_documents",
        sa.Column("corpus", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("source", sa.String(length=240), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_of", sa.String(length=120), nullable=True),
        sa.Column(
            "doc_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "embedding",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("embedding_model", sa.String(length=60), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
    )
    with op.batch_alter_table("knowledge_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_chunk_of"), ["chunk_of"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_knowledge_documents_corpus"), ["corpus"], unique=False)
        batch_op.create_index(
            "ix_knowledge_documents_corpus_chunk", ["corpus", "chunk_index"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_knowledge_documents_slug"), ["slug"], unique=True)

    op.create_table(
        "missions",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("building", sa.String(length=40), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("skill_slug", sa.String(length=40), nullable=False),
        sa.Column("briefing", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column(
            "success_criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "artifacts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("debrief", sa.Text(), nullable=False),
        sa.Column("required_level", sa.Integer(), nullable=False),
        sa.Column("required_rank", sa.String(length=40), nullable=True),
        sa.Column(
            "prerequisite_mission_slugs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "concept_slugs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("par_seconds", sa.Integer(), nullable=False),
        sa.Column("xp_multiplier", sa.Float(), nullable=False),
        sa.Column("is_boss", sa.Boolean(), nullable=False),
        sa.Column("is_daily_eligible", sa.Boolean(), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("tier BETWEEN 1 AND 10", name=op.f("ck_missions_tier_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_missions")),
    )
    with op.batch_alter_table("missions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_missions_building"), ["building"], unique=False)
        batch_op.create_index("ix_missions_building_tier", ["building", "tier"], unique=False)
        batch_op.create_index(batch_op.f("ix_missions_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_missions_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_missions_skill_slug"), ["skill_slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_missions_slug"), ["slug"], unique=True)

    op.create_table(
        "projects",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column("required_level", sa.Integer(), nullable=False),
        sa.Column("required_rank", sa.String(length=40), nullable=True),
        sa.Column(
            "architecture",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "milestones",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "defense_question_slugs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_slug"), ["slug"], unique=True)

    op.create_table(
        "questions",
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("skill_slug", sa.String(length=40), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("interview_level", sa.String(length=16), nullable=False),
        sa.Column(
            "concept_slugs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expected_answer", sa.Text(), nullable=False),
        sa.Column("ideal_senior_answer", sa.Text(), nullable=False),
        sa.Column("common_wrong_answer", sa.Text(), nullable=False),
        sa.Column(
            "rubric",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "hints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "followups",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("par_seconds", sa.Integer(), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_questions_category_tier_kind", ["category", "tier", "kind"], unique=False
        )
        batch_op.create_index("ix_questions_level", ["interview_level"], unique=False)
        batch_op.create_index(batch_op.f("ix_questions_skill_slug"), ["skill_slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_questions_slug"), ["slug"], unique=True)

    op.create_table(
        "skills",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("building", sa.String(length=40), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
    )
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skills_slug"), ["slug"], unique=True)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "concept_edges",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("relation", sa.String(length=24), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["concepts.id"],
            name=op.f("fk_concept_edges_source_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["concepts.id"],
            name=op.f("fk_concept_edges_target_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_edges")),
        sa.UniqueConstraint("source_id", "target_id", "relation", name="uq_concept_edge"),
    )
    with op.batch_alter_table("concept_edges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_concept_edges_source_id"), ["source_id"], unique=False)
        batch_op.create_index("ix_concept_edges_target", ["target_id", "relation"], unique=False)

    op.create_table(
        "mission_steps",
        sa.Column("mission_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("challenge_slug", sa.String(length=120), nullable=True),
        sa.Column("question_slug", sa.String(length=120), nullable=True),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
            name=op.f("fk_mission_steps_mission_id_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_steps")),
        sa.UniqueConstraint("mission_id", "position", name="uq_mission_step_position"),
    )
    with op.batch_alter_table("mission_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mission_steps_challenge_slug"), ["challenge_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mission_steps_mission_id"), ["mission_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mission_steps_question_slug"), ["question_slug"], unique=False
        )

    op.create_table(
        "player_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=60), nullable=False),
        sa.Column("avatar_seed", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("total_xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("rank", sa.String(length=40), nullable=False),
        sa.Column("coins", sa.Integer(), nullable=False),
        sa.Column("reputation", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_active_date", sa.Date(), nullable=True),
        sa.Column("missions_completed", sa.Integer(), nullable=False),
        sa.Column("challenges_passed", sa.Integer(), nullable=False),
        sa.Column("questions_answered", sa.Integer(), nullable=False),
        sa.Column("bosses_defeated", sa.Integer(), nullable=False),
        sa.Column("incidents_resolved", sa.Integer(), nullable=False),
        sa.Column("total_practice_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "unlocked_buildings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("preferred_mentor", sa.String(length=32), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_player_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_profiles")),
    )
    with op.batch_alter_table("player_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_player_profiles_total_xp"), ["total_xp"], unique=False)
        batch_op.create_index(batch_op.f("ix_player_profiles_user_id"), ["user_id"], unique=True)

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_tokens_jti"), ["jti"], unique=True)
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_refresh_tokens_user_revoked", ["user_id", "revoked"], unique=False
        )

    op.create_table(
        "skill_nodes",
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "tier_range",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("unlock_level", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["skill_nodes.id"],
            name=op.f("fk_skill_nodes_parent_id_skill_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_nodes_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_nodes")),
    )
    with op.batch_alter_table("skill_nodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skill_nodes_skill_id"), ["skill_id"], unique=False)
        batch_op.create_index(
            "ix_skill_nodes_skill_parent", ["skill_id", "parent_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_skill_nodes_slug"), ["slug"], unique=True)

    op.create_table(
        "code_submissions",
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("challenge_slug", sa.String(length=120), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=False),
        sa.Column("stderr", sa.Text(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("peak_memory_kb", sa.Integer(), nullable=True),
        sa.Column("timed_out", sa.Boolean(), nullable=False),
        sa.Column(
            "test_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sandbox_mode", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_code_submissions_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_submissions")),
    )
    with op.batch_alter_table("code_submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_code_submissions_challenge_slug"), ["challenge_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_code_submissions_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index(
            "ix_code_submissions_profile_time", ["profile_id", "created_at"], unique=False
        )

    op.create_table(
        "concept_progress",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("concept_slug", sa.String(length=120), nullable=False),
        sa.Column("skill_slug", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("stability_days", sa.Float(), nullable=False),
        sa.Column("ease", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Float(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Integer(), nullable=False),
        sa.Column("mastery", sa.Float(), nullable=False),
        sa.Column("peak_mastery", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("highest_tier_cleared", sa.Integer(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_correct", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_incorrect", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_decay_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("decay_alert_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_concept_progress_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_progress")),
        sa.UniqueConstraint("profile_id", "concept_slug", name="uq_concept_progress"),
    )
    with op.batch_alter_table("concept_progress", schema=None) as batch_op:
        batch_op.create_index("ix_concept_progress_due", ["profile_id", "due_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_concept_progress_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index(
            "ix_concept_progress_skill", ["profile_id", "skill_slug"], unique=False
        )

    op.create_table(
        "daily_challenges",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("for_date", sa.Date(), nullable=False),
        sa.Column(
            "slots",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "generation_reason",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "completed_slots",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("xp_awarded", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_daily_challenges_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_challenges")),
        sa.UniqueConstraint("profile_id", "for_date", name="uq_daily_per_day"),
    )
    with op.batch_alter_table("daily_challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_daily_challenges_for_date"), ["for_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_daily_challenges_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "evaluations",
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("target_type", sa.String(length=24), nullable=False),
        sa.Column("target_ref", sa.String(length=120), nullable=True),
        sa.Column("dataset_slug", sa.String(length=120), nullable=True),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("retrieval_precision", sa.Float(), nullable=True),
        sa.Column("retrieval_recall", sa.Float(), nullable=True),
        sa.Column("context_relevance", sa.Float(), nullable=True),
        sa.Column("faithfulness", sa.Float(), nullable=True),
        sa.Column("answer_relevance", sa.Float(), nullable=True),
        sa.Column("groundedness", sa.Float(), nullable=True),
        sa.Column(
            "extra_metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("cases_total", sa.Integer(), nullable=False),
        sa.Column("cases_passed", sa.Integer(), nullable=False),
        sa.Column(
            "results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("verdict", sa.String(length=24), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_evaluations_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluations")),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evaluations_profile_id"), ["profile_id"], unique=False)
        batch_op.create_index(
            "ix_evaluations_profile_target", ["profile_id", "target_type"], unique=False
        )

    op.create_table(
        "interview_sessions",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column(
            "focus_categories",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("persona", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_questions", sa.Integer(), nullable=False),
        sa.Column("questions_asked", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column(
            "dimension_scores",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("verdict", sa.String(length=32), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "strengths",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "gaps",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "adaptive_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_interview_sessions_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_sessions")),
    )
    with op.batch_alter_table("interview_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_interview_sessions_profile", ["profile_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interview_sessions_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "leaderboard_entries",
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("period_key", sa.String(length=16), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=60), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("rank", sa.String(length=40), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_leaderboard_entries_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leaderboard_entries")),
        sa.UniqueConstraint("period", "period_key", "profile_id", name="uq_leaderboard_slot"),
    )
    with op.batch_alter_table("leaderboard_entries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_leaderboard_rank", ["period", "period_key", "position"], unique=False
        )

    op.create_table(
        "learning_events",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("concept_slug", sa.String(length=120), nullable=True),
        sa.Column("skill_slug", sa.String(length=40), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_learning_events_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_events")),
    )
    with op.batch_alter_table("learning_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_learning_events_concept", ["profile_id", "concept_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_events_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index(
            "ix_learning_events_profile_time", ["profile_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_events_skill_slug"), ["skill_slug"], unique=False
        )
        batch_op.create_index("ix_learning_events_type", ["profile_id", "event_type"], unique=False)

    op.create_table(
        "mission_attempts",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("mission_slug", sa.String(length=120), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("xp_awarded", sa.Integer(), nullable=False),
        sa.Column("coins_awarded", sa.Integer(), nullable=False),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column(
            "step_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_daily", sa.Boolean(), nullable=False),
        sa.Column("is_retention_repair", sa.Boolean(), nullable=False),
        sa.Column(
            "feedback",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_mission_attempts_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_attempts")),
    )
    with op.batch_alter_table("mission_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_mission_attempts_mission", ["mission_slug", "profile_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mission_attempts_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index(
            "ix_mission_attempts_profile_status", ["profile_id", "status"], unique=False
        )

    op.create_table(
        "mistake_records",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("pattern", sa.String(length=80), nullable=False),
        sa.Column("concept_slug", sa.String(length=120), nullable=True),
        sa.Column("skill_slug", sa.String(length=40), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("why_it_matters", sa.Text(), nullable=False),
        sa.Column("correct_approach", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clean_streak", sa.Integer(), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_mistake_records_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mistake_records")),
        sa.UniqueConstraint("profile_id", "pattern", name="uq_mistake_profile_pattern"),
    )
    with op.batch_alter_table("mistake_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mistake_records_concept_slug"), ["concept_slug"], unique=False
        )
        batch_op.create_index("ix_mistake_records_open", ["profile_id", "resolved"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_mistake_records_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "player_achievements",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("achievement_slug", sa.String(length=80), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seen", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_player_achievements_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_achievements")),
        sa.UniqueConstraint("profile_id", "achievement_slug", name="uq_player_achievement"),
    )
    with op.batch_alter_table("player_achievements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_achievements_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "player_badges",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("badge_slug", sa.String(length=80), nullable=False),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seen", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_player_badges_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_badges")),
        sa.UniqueConstraint("profile_id", "badge_slug", name="uq_player_badge"),
    )
    with op.batch_alter_table("player_badges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_badges_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "project_progress",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("project_slug", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "milestone_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("defense_score", sa.Float(), nullable=True),
        sa.Column("xp_awarded", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_project_progress_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_progress")),
        sa.UniqueConstraint("profile_id", "project_slug", name="uq_project_progress"),
    )
    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_progress_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "skill_progress",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("skill_slug", sa.String(length=40), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("mastery", sa.Float(), nullable=False),
        sa.Column("effective_mastery", sa.Float(), nullable=False),
        sa.Column("peak_mastery", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("forgetting_score", sa.Float(), nullable=False),
        sa.Column("highest_tier_cleared", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Integer(), nullable=False),
        sa.Column("streak", sa.Integer(), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "unlocked_nodes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_skill_progress_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_progress")),
        sa.UniqueConstraint("profile_id", "skill_slug", name="uq_skill_progress_profile_skill"),
    )
    with op.batch_alter_table("skill_progress", schema=None) as batch_op:
        batch_op.create_index("ix_skill_progress_mastery", ["profile_id", "mastery"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_skill_progress_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "traces",
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Float(), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "trace_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_traces_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traces")),
    )
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_traces_profile_id"), ["profile_id"], unique=False)
        batch_op.create_index("ix_traces_profile_time", ["profile_id", "started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_traces_request_id"), ["request_id"], unique=False)

    op.create_table(
        "xp_transactions",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("skill_slug", sa.String(length=40), nullable=True),
        sa.Column("reference_type", sa.String(length=32), nullable=True),
        sa.Column("reference_slug", sa.String(length=120), nullable=True),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_xp_transactions_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xp_transactions")),
    )
    with op.batch_alter_table("xp_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_xp_transactions_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index(
            "ix_xp_transactions_profile_time", ["profile_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_xp_transactions_skill_slug"), ["skill_slug"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_xp_transactions_source"), ["source"], unique=False)

    op.create_table(
        "agent_runs",
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("graph_slug", sa.String(length=80), nullable=False),
        sa.Column(
            "input_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "final_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column(
            "state_history",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "node_visits",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("steps", sa.Integer(), nullable=False),
        sa.Column("halted_reason", sa.String(length=60), nullable=True),
        sa.Column("needs_human_approval", sa.Boolean(), nullable=False),
        sa.Column("human_decision", sa.String(length=16), nullable=True),
        sa.Column("trace_id", sa.Uuid(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column(
            "token_usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_agent_runs_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["traces.id"],
            name=op.f("fk_agent_runs_trace_id_traces"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_graph_slug"), ["graph_slug"], unique=False)
        batch_op.create_index("ix_agent_runs_profile", ["profile_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_profile_id"), ["profile_id"], unique=False)

    op.create_table(
        "challenge_attempts",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("challenge_slug", sa.String(length=120), nullable=False),
        sa.Column("mission_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("submitted_code", sa.Text(), nullable=False),
        sa.Column("tests_passed", sa.Integer(), nullable=False),
        sa.Column("tests_total", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("runtime_ms", sa.Float(), nullable=False),
        sa.Column("stdout", sa.Text(), nullable=False),
        sa.Column("stderr", sa.Text(), nullable=False),
        sa.Column(
            "test_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("explanation_score", sa.Float(), nullable=True),
        sa.Column("complexity_answer", sa.String(length=80), nullable=True),
        sa.Column("code_quality_score", sa.Float(), nullable=True),
        sa.Column("speedup_factor", sa.Float(), nullable=True),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mission_attempt_id"],
            ["mission_attempts.id"],
            name=op.f("fk_challenge_attempts_mission_attempt_id_mission_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_challenge_attempts_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenge_attempts")),
    )
    with op.batch_alter_table("challenge_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_challenge_attempts_profile", ["profile_id", "challenge_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_challenge_attempts_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "interview_turns",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question_slug", sa.String(length=120), nullable=True),
        sa.Column("parent_position", sa.Integer(), nullable=True),
        sa.Column("is_followup", sa.Boolean(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column(
            "selected_option_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "dimension_scores",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "missing_points",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("interviewer_reaction", sa.Text(), nullable=False),
        sa.Column("graded_by", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_interview_turns_session_id_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_turns")),
    )
    with op.batch_alter_table("interview_turns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interview_turns_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            "ix_interview_turns_session_pos", ["session_id", "position"], unique=False
        )

    op.create_table(
        "journal_entries",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("mission_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("context_slug", sa.String(length=120), nullable=True),
        sa.Column("what_i_learned", sa.Text(), nullable=False),
        sa.Column("mistake_made", sa.Text(), nullable=False),
        sa.Column("would_do_differently", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "concept_slugs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("resurfaced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mission_attempt_id"],
            ["mission_attempts.id"],
            name=op.f("fk_journal_entries_mission_attempt_id_mission_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_journal_entries_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
    )
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_journal_entries_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index("ix_journal_profile_time", ["profile_id", "created_at"], unique=False)

    op.create_table(
        "question_attempts",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("question_slug", sa.String(length=120), nullable=False),
        sa.Column("interview_session_id", sa.Uuid(), nullable=True),
        sa.Column("mission_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column(
            "selected_option_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "score_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "missing_points",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=False),
        sa.Column("graded_by", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["interview_session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_question_attempts_interview_session_id_interview_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["mission_attempt_id"],
            ["mission_attempts.id"],
            name=op.f("fk_question_attempts_mission_attempt_id_mission_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_question_attempts_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_attempts")),
    )
    with op.batch_alter_table("question_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_question_attempts_profile", ["profile_id", "question_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_attempts_profile_id"), ["profile_id"], unique=False
        )
        batch_op.create_index(
            "ix_question_attempts_recent", ["profile_id", "created_at"], unique=False
        )

    op.create_table(
        "rag_experiments",
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("corpus", sa.String(length=60), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=True),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("embedding_model", sa.String(length=60), nullable=False),
        sa.Column("use_reranker", sa.Boolean(), nullable=False),
        sa.Column("use_hybrid", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata_filter",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column(
            "retrieved",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("trace_id", sa.Uuid(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column(
            "token_usage",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["player_profiles.id"],
            name=op.f("fk_rag_experiments_profile_id_player_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["traces.id"],
            name=op.f("fk_rag_experiments_trace_id_traces"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rag_experiments")),
    )
    with op.batch_alter_table("rag_experiments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_rag_experiments_profile", ["profile_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_rag_experiments_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "spans",
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("span_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column(
            "input_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=True),
        sa.Column("evaluation_score", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "span_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["spans.id"], name=op.f("fk_spans_parent_id_spans"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"], ["traces.id"], name=op.f("fk_spans_trace_id_traces"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spans")),
    )
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_spans_trace_id"), ["trace_id"], unique=False)
        batch_op.create_index("ix_spans_trace_parent", ["trace_id", "parent_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.drop_index("ix_spans_trace_parent")
        batch_op.drop_index(batch_op.f("ix_spans_trace_id"))

    op.drop_table("spans")
    with op.batch_alter_table("rag_experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rag_experiments_profile_id"))
        batch_op.drop_index("ix_rag_experiments_profile")

    op.drop_table("rag_experiments")
    with op.batch_alter_table("question_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_question_attempts_recent")
        batch_op.drop_index(batch_op.f("ix_question_attempts_profile_id"))
        batch_op.drop_index("ix_question_attempts_profile")

    op.drop_table("question_attempts")
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_journal_profile_time")
        batch_op.drop_index(batch_op.f("ix_journal_entries_profile_id"))

    op.drop_table("journal_entries")
    with op.batch_alter_table("interview_turns", schema=None) as batch_op:
        batch_op.drop_index("ix_interview_turns_session_pos")
        batch_op.drop_index(batch_op.f("ix_interview_turns_session_id"))

    op.drop_table("interview_turns")
    with op.batch_alter_table("challenge_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_challenge_attempts_profile_id"))
        batch_op.drop_index("ix_challenge_attempts_profile")

    op.drop_table("challenge_attempts")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_profile_id"))
        batch_op.drop_index("ix_agent_runs_profile")
        batch_op.drop_index(batch_op.f("ix_agent_runs_graph_slug"))

    op.drop_table("agent_runs")
    with op.batch_alter_table("xp_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_xp_transactions_source"))
        batch_op.drop_index(batch_op.f("ix_xp_transactions_skill_slug"))
        batch_op.drop_index("ix_xp_transactions_profile_time")
        batch_op.drop_index(batch_op.f("ix_xp_transactions_profile_id"))

    op.drop_table("xp_transactions")
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_traces_request_id"))
        batch_op.drop_index("ix_traces_profile_time")
        batch_op.drop_index(batch_op.f("ix_traces_profile_id"))

    op.drop_table("traces")
    with op.batch_alter_table("skill_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_progress_profile_id"))
        batch_op.drop_index("ix_skill_progress_mastery")

    op.drop_table("skill_progress")
    with op.batch_alter_table("project_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_progress_profile_id"))

    op.drop_table("project_progress")
    with op.batch_alter_table("player_badges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_badges_profile_id"))

    op.drop_table("player_badges")
    with op.batch_alter_table("player_achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_achievements_profile_id"))

    op.drop_table("player_achievements")
    with op.batch_alter_table("mistake_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mistake_records_profile_id"))
        batch_op.drop_index("ix_mistake_records_open")
        batch_op.drop_index(batch_op.f("ix_mistake_records_concept_slug"))

    op.drop_table("mistake_records")
    with op.batch_alter_table("mission_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_mission_attempts_profile_status")
        batch_op.drop_index(batch_op.f("ix_mission_attempts_profile_id"))
        batch_op.drop_index("ix_mission_attempts_mission")

    op.drop_table("mission_attempts")
    with op.batch_alter_table("learning_events", schema=None) as batch_op:
        batch_op.drop_index("ix_learning_events_type")
        batch_op.drop_index(batch_op.f("ix_learning_events_skill_slug"))
        batch_op.drop_index("ix_learning_events_profile_time")
        batch_op.drop_index(batch_op.f("ix_learning_events_profile_id"))
        batch_op.drop_index("ix_learning_events_concept")

    op.drop_table("learning_events")
    with op.batch_alter_table("leaderboard_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_leaderboard_rank")

    op.drop_table("leaderboard_entries")
    with op.batch_alter_table("interview_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interview_sessions_profile_id"))
        batch_op.drop_index("ix_interview_sessions_profile")

    op.drop_table("interview_sessions")
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index("ix_evaluations_profile_target")
        batch_op.drop_index(batch_op.f("ix_evaluations_profile_id"))

    op.drop_table("evaluations")
    with op.batch_alter_table("daily_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_challenges_profile_id"))
        batch_op.drop_index(batch_op.f("ix_daily_challenges_for_date"))

    op.drop_table("daily_challenges")
    with op.batch_alter_table("concept_progress", schema=None) as batch_op:
        batch_op.drop_index("ix_concept_progress_skill")
        batch_op.drop_index(batch_op.f("ix_concept_progress_profile_id"))
        batch_op.drop_index("ix_concept_progress_due")

    op.drop_table("concept_progress")
    with op.batch_alter_table("code_submissions", schema=None) as batch_op:
        batch_op.drop_index("ix_code_submissions_profile_time")
        batch_op.drop_index(batch_op.f("ix_code_submissions_profile_id"))
        batch_op.drop_index(batch_op.f("ix_code_submissions_challenge_slug"))

    op.drop_table("code_submissions")
    with op.batch_alter_table("skill_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_nodes_slug"))
        batch_op.drop_index("ix_skill_nodes_skill_parent")
        batch_op.drop_index(batch_op.f("ix_skill_nodes_skill_id"))

    op.drop_table("skill_nodes")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_refresh_tokens_user_revoked")
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_jti"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("player_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_profiles_user_id"))
        batch_op.drop_index(batch_op.f("ix_player_profiles_total_xp"))

    op.drop_table("player_profiles")
    with op.batch_alter_table("mission_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mission_steps_question_slug"))
        batch_op.drop_index(batch_op.f("ix_mission_steps_mission_id"))
        batch_op.drop_index(batch_op.f("ix_mission_steps_challenge_slug"))

    op.drop_table("mission_steps")
    with op.batch_alter_table("concept_edges", schema=None) as batch_op:
        batch_op.drop_index("ix_concept_edges_target")
        batch_op.drop_index(batch_op.f("ix_concept_edges_source_id"))

    op.drop_table("concept_edges")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skills_slug"))

    op.drop_table("skills")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_slug"))
        batch_op.drop_index(batch_op.f("ix_questions_skill_slug"))
        batch_op.drop_index("ix_questions_level")
        batch_op.drop_index("ix_questions_category_tier_kind")

    op.drop_table("questions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_slug"))

    op.drop_table("projects")
    with op.batch_alter_table("missions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_missions_slug"))
        batch_op.drop_index(batch_op.f("ix_missions_skill_slug"))
        batch_op.drop_index(batch_op.f("ix_missions_kind"))
        batch_op.drop_index(batch_op.f("ix_missions_category"))
        batch_op.drop_index("ix_missions_building_tier")
        batch_op.drop_index(batch_op.f("ix_missions_building"))

    op.drop_table("missions")
    with op.batch_alter_table("knowledge_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_slug"))
        batch_op.drop_index("ix_knowledge_documents_corpus_chunk")
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_corpus"))
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_chunk_of"))

    op.drop_table("knowledge_documents")
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concepts_slug"))
        batch_op.drop_index(batch_op.f("ix_concepts_skill_slug"))
        batch_op.drop_index(batch_op.f("ix_concepts_skill_node_slug"))
        batch_op.drop_index("ix_concepts_category_difficulty")
        batch_op.drop_index(batch_op.f("ix_concepts_category"))

    op.drop_table("concepts")
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_challenges_slug"))
        batch_op.drop_index(batch_op.f("ix_challenges_skill_slug"))
        batch_op.drop_index("ix_challenges_category_tier")
        batch_op.drop_index(batch_op.f("ix_challenges_category"))

    op.drop_table("challenges")
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_badges_slug"))

    op.drop_table("badges")
    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_achievements_slug"))

    op.drop_table("achievements")
    # ### end Alembic commands ###
